#!/bin/bash
set -euo pipefail

sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
sudo apt-get update
xx- sudo apt-get install -t trusty-backports shellcheck

